### PR TITLE
WIP: CheckboxGroup

### PR DESCRIPTION
**Pull request by linbingquan**
Excuse me, How to make the `Checkbox` component to callback the parent component `CheckboxGroup`'s function `changed`.

### CODE REVIEW

**Comment by mxdi9i7** [comment]
@linbingquan There's a `changed` function prop in Checkbox, you can use that to connect with the group's `changed` prop

**Comment by linbingquan** [comment]
@mxdi9i7 I had connect `Checkbox` and `CheckboxGroup` component `changed` function, I don't konw how to get other children component state.

**Comment by mxdi9i7** [comment]
@linbingquan  hi, is this pr ready?

**Comment by linbingquan** [comment]
> @linbingquan hi, is this pr ready?

TBH, this is just basic function. I am not sure it doesn't has any bug.

**Pull request closed without merging**
